# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ProiectSSC/HardwareZYBO/HardwareZYBO.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/bd_afc3_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_53/bd_afc3_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_66/bd_afc3_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_67/bd_afc3_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_68/bd_afc3_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_69/bd_afc3_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_70/bd_afc3_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_71/bd_afc3_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_72/bd_afc3_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_73/bd_afc3_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_74/bd_afc3_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_75/bd_afc3_m07s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_76/bd_afc3_m07arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_77/bd_afc3_m07rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_78/bd_afc3_m07awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_79/bd_afc3_m07wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_80/bd_afc3_m07bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_81/bd_afc3_m07e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_82/bd_afc3_m08s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_83/bd_afc3_m08arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_84/bd_afc3_m08rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_85/bd_afc3_m08awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_86/bd_afc3_m08wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_87/bd_afc3_m08bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_88/bd_afc3_m08e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_89/bd_afc3_m09s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_90/bd_afc3_m09arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_91/bd_afc3_m09rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_92/bd_afc3_m09awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_93/bd_afc3_m09wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_94/bd_afc3_m09bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_95/bd_afc3_m09e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_m02s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_m02arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_m02rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_m02awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_m02wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_m02bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_m03s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_m03arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_m03rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_m03awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_m03wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_m03bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_m04s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_m04arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_m04rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_m04awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_m04wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m04bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m05s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m05arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m05rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m05awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m05wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_66/bd_afc3_m05bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_68/bd_afc3_m06s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_69/bd_afc3_m06arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_70/bd_afc3_m06rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_71/bd_afc3_m06awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_72/bd_afc3_m06wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_73/bd_afc3_m06bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_75/bd_afc3_m07s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_76/bd_afc3_m07arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_77/bd_afc3_m07rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_78/bd_afc3_m07awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_79/bd_afc3_m07wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_80/bd_afc3_m07bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_82/bd_afc3_m08s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_83/bd_afc3_m08arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_84/bd_afc3_m08rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_85/bd_afc3_m08awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_86/bd_afc3_m08wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_87/bd_afc3_m08bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_89/bd_afc3_m09s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_90/bd_afc3_m09arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_91/bd_afc3_m09rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_92/bd_afc3_m09awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_93/bd_afc3_m09wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_94/bd_afc3_m09bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/ProiectSSC/HardwareZYBO/HardwareZYBO.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/bd_afc3_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_53/bd_afc3_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_66/bd_afc3_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_67/bd_afc3_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_68/bd_afc3_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_69/bd_afc3_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_70/bd_afc3_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_71/bd_afc3_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_72/bd_afc3_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_73/bd_afc3_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_74/bd_afc3_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_75/bd_afc3_m07s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_76/bd_afc3_m07arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_77/bd_afc3_m07rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_78/bd_afc3_m07awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_79/bd_afc3_m07wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_80/bd_afc3_m07bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_81/bd_afc3_m07e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_82/bd_afc3_m08s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_83/bd_afc3_m08arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_84/bd_afc3_m08rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_85/bd_afc3_m08awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_86/bd_afc3_m08wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_87/bd_afc3_m08bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_88/bd_afc3_m08e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_89/bd_afc3_m09s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_90/bd_afc3_m09arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_91/bd_afc3_m09rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_92/bd_afc3_m09awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_93/bd_afc3_m09wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_94/bd_afc3_m09bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_95/bd_afc3_m09e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/bd_afc3_m02s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/bd_afc3_m02arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_m02rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_m02awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_m02wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_m02bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_47/bd_afc3_m03s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_48/bd_afc3_m03arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_m03rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_m03awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_m03wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_52/bd_afc3_m03bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_54/bd_afc3_m04s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_m04arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_m04rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_m04awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_m04wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m04bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m05s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m05arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m05rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m05awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_65/bd_afc3_m05wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_66/bd_afc3_m05bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_68/bd_afc3_m06s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_69/bd_afc3_m06arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_70/bd_afc3_m06rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_71/bd_afc3_m06awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_72/bd_afc3_m06wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_73/bd_afc3_m06bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_75/bd_afc3_m07s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_76/bd_afc3_m07arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_77/bd_afc3_m07rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_78/bd_afc3_m07awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_79/bd_afc3_m07wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_80/bd_afc3_m07bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_82/bd_afc3_m08s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_83/bd_afc3_m08arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_84/bd_afc3_m08rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_85/bd_afc3_m08awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_86/bd_afc3_m08wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_87/bd_afc3_m08bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_89/bd_afc3_m09s2a_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_90/bd_afc3_m09arn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_91/bd_afc3_m09rn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_92/bd_afc3_m09awn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_93/bd_afc3_m09wn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_94/bd_afc3_m09bn_0_ooc.xdc

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ProiectSSC/HardwareZYBO/HardwareZYBO.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
