domain_path: D:\ProiectSSC\SoftwareWBuffer\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Xillinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
